name = "GeoDataExplorer"
uuid = "4991c337-ea68-4580-b508-08cf157e32a8"
version = "0.1.0"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com>"]

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
PyramidScheme = "ec211b67-1c2c-4319-878f-eaee078ee145"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
ArchGDAL = "0.10.11"
Colors = "0.13.1"
GeoDataFrames = "0.4.2"
GeometryBasics = "0.5.10"
GeometryOps = "0.1.37"
Makie = "0.24.8"
NCDatasets = "0.14.10"
PyramidScheme = "0.1.2"
Rasters = "0.14.7"
Tables = "1.12.1"
